name: build-main
run-name: build-main
on:
  push:
    branches:
      - main
  schedule:
    # every day at midnight
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osgeo/gdal
      # see https://github.com/actions/runner/issues/2033#issuecomment-1598547465
      options: --user 1001
    permissions:
      contents: write
    name: main
    steps:
      - run: apt update

      - run: apt install -y git

      - uses: actions/checkout@v3

      - run: sh ./run.sh

      - run: ls ./files

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
