name: build-main
run-name: build-main
on:
  push:
    branches:
      - main
  schedule:
    # every day at midnight
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/osgeo/gdal
    permissions:
      contents: write
    name: download and save data
    steps:
      - uses: actions/checkout@v3

      - run: sh ./run.sh

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
